name: Deploy static placeholder to Azure Web App - HospiceMD-GPT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create placeholder file
        run: |
          echo "<html><body><h1>HospiceMD is live!</h1></body></html>" > index.html
          zip -r release.zip index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C9A98B6B28AF4158AA16F23D9FAD8879 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6F302411367C41F6A5569CB48286DC49 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_52C58ABED4524F98BB53E39A786049DC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HospiceMD-GPT'
          slot-name: 'Production'
          package: .
